[package]
name = "prop_house"
version = "0.1.0"
description = "Public infrastructure by Nouns DAO"

[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test ."

# Note: currently testing doesn't work with dependencies
[dependencies]
quaireaux_data_structures = { git = "https://github.com/keep-starknet-strange/quaireaux" }

[[target.starknet-contract]]
