services:
  db:
    image: bitnami/postgresql:11.14.0-debian-10-r28
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
     - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080